### PR TITLE
Remove deprecated import of SafeConfigParser

### LINKED ISSUE #453: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2.
```
DeprecationWarning: The SafeConfigParser class has been renamed to ConfigParser in Python 3.2. This alias will be removed in future versions. Use ConfigParser directly instead.
```

### PR DESCRIPTION
**Pull request by scottgigante**
Closes #453

### CODE REVIEW

**Comment by scottgigante** [comment]
Bump!

**Comment by sirosen** [comment]
Sorry for missing this. I've put this into my queue for tomorrow morning -- I want to double check docs and make sure there are no weird considerations to consider. (It seems totally fine right now, but I want to take a few hours to think about it and make sure I'm not missing anything.)

**Comment by sirosen** [comment]
I am going to squash-merge this one just to clean up. I prefer handling compatibility with multiple pythons like this, in the imports, rather than buried inside of things (the way it was before). Thanks for the PR!

**Comment by scottgigante** [comment]
Thanks for the merge!

**Pull request merged**
