### PR TITLE
[WIP] Add doc to mp plugin

### PR DESCRIPTION
**Pull request by artragis**
From a discussion we add on gitter I add some documentation to understand the behaviour of mp plugin.

To help understand it better I created a flowchart thanks to mermaid, the rendering is : 

screenshot-2017-11-17 running tests in parallel with multiple processes nose2 0 6 0 documentation 1

### CODE REVIEW

**Comment by ptthiem** [comment]
..and reformat things for pep8 ;)

**Comment by artragis** [comment]
not a full reformat, it's just that as I tried to understand the code, I wanted to get rid of the pycharm warnings.

**Comment by katrinabrock** [comment]
Once this is in a state that @ptthiem approves, it's fine to merge by me.

**Comment by sirosen** [comment]
As this has been sitting for several years and never made it over the finish line, I'm going to close. Feel free to reopen if there's active interest.

**Pull request closed without merging**
