### PR TITLE
Restore exception context when passed in loader's _makeFailedTest method

### LINKED ISSUE #48: Loader errors throw away tracebacks and exception detail
For instance if a generator test throws an AttributeError, the details of the attribute error are lost and the user only sees "AttributeError" -- not very helpful.

### PR DESCRIPTION
**Pull request by dlax**
Closes #48.

### CODE REVIEW

**Comment by dlax** [comment]
Hmm, this does not actually fixes #48 completly since the exception context is not forwarded down to the test failure. Will work further on this...

**Comment by dlax** [comment]
Pushed a new version.

**Comment by dlax** [comment]
Another version hopefully suitable for Python 3...

**Comment by thedrow** [comment]
Can you ensure all branches are covered by tests?

**Pull request merged**
